"""Voice fingerprint schemas.

A VoiceFingerprint anchors a character's idiolect: lexical statistics,
preferred/banned phrases, verbal tics, and 5–8 verbatim sample lines
that get injected as few-shot context whenever that character speaks.

Phase 2 stores fingerprints generated by the Character Forge agent (LLM
inference). Phase 3 adds a statistical extractor (``voice/extractor.py``)
that derives the lexical numbers from sample text instead of asking an
LLM for them.
"""

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field


class LexicalFingerprint(BaseModel):
    """Statistical signature of a character's speech.

    Values are best-effort estimates from the Character Forge / extractor.
    They get used as soft targets — the Voice Critic flags dialogue that
    deviates from them.
    """

    model_config = ConfigDict(extra="forbid")

    avg_sentence_words: float = Field(ge=1.0, le=80.0, default=14.0)
    sentence_length_stddev: float = Field(ge=0.0, le=40.0, default=6.0)
    contraction_rate: float = Field(ge=0.0, le=1.0, default=0.4)
    formality: int = Field(ge=1, le=10, default=5)
    style_register: str = Field(
        default="casual",
        description="casual | professional | archaic | street | academic | military | clinical | poetic | rustic",
    )
    dialect_markers: List[str] = Field(default_factory=list)
    profanity_rate: float = Field(ge=0.0, le=1.0, default=0.0)
    hedging_rate: float = Field(ge=0.0, le=1.0, default=0.1)


class VoiceFingerprint(BaseModel):
    """Full character voice spec.

    ``sample_lines`` is the highest-leverage field: 5–8 verbatim lines a
    LLM can use as few-shot anchors when writing dialogue or interiority
    for this character.
    """

    model_config = ConfigDict(extra="forbid")

    lexical: LexicalFingerprint = Field(default_factory=LexicalFingerprint)
    preferred_phrases: List[str] = Field(
        default_factory=list,
        description="Things the character habitually says (e.g. 'mate', 'reckon').",
    )
    banned_phrases: List[str] = Field(
        default_factory=list,
        description="Things the character would NEVER say. Strong anti-pattern signal.",
    )
    verbal_tics: List[str] = Field(
        default_factory=list,
        description="Interruptions, trailing '...', filler words ('you know', 'like').",
    )
    catchphrases: List[str] = Field(
        default_factory=list,
        description="Signature lines or repeated jokes (use sparingly).",
    )
    sample_lines: List[str] = Field(
        default_factory=list,
        description="5–8 verbatim lines the character could plausibly say. Used as few-shot.",
    )
    silence_style: Optional[str] = Field(
        default=None,
        description="How this character avoids speaking: deflects, jokes, changes subject, stares, etc.",
    )
