"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-fallback-dev-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True") == "True"

ALLOWED_HOSTS = ["writer.bdgroups.cloud", "127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'stories',
    'stories_v2',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---------------------------------------------------------------------------
# Django REST Framework
# ---------------------------------------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
}

# ---------------------------------------------------------------------------
# MongoDB (PyMongo direct)
# ---------------------------------------------------------------------------
MONGODB_URI = os.getenv("MONGODB_URI", "mongodb://localhost:27017")
MONGODB_DB_NAME = os.getenv("MONGODB_DB_NAME", "ai_writer")

# ---------------------------------------------------------------------------
# Together AI LLM
# ---------------------------------------------------------------------------
TOGETHER_API_KEY = os.getenv("TOGETHER_API_KEY", "")

# Serverless model routing. TOGETHER_MODEL remains a legacy/default fallback:
# if an existing deployment already sets TOGETHER_MODEL, all unconfigured
# roles still inherit it.
TOGETHER_DEFAULT_MODEL = os.getenv(
    "TOGETHER_DEFAULT_MODEL",
    os.getenv("TOGETHER_MODEL", "MiniMaxAI/MiniMax-M2.7"),
)
TOGETHER_MODEL = os.getenv("TOGETHER_MODEL", TOGETHER_DEFAULT_MODEL)

TOGETHER_PROFILE_MODEL = os.getenv(
    "TOGETHER_PROFILE_MODEL", TOGETHER_DEFAULT_MODEL)
TOGETHER_PLANNER_MODEL = os.getenv(
    "TOGETHER_PLANNER_MODEL", "moonshotai/Kimi-K2.5")
TOGETHER_WRITER_MODEL = os.getenv(
    "TOGETHER_WRITER_MODEL", "moonshotai/Kimi-K2.5")
TOGETHER_REVIEWER_MODEL = os.getenv(
    "TOGETHER_REVIEWER_MODEL", "openai/gpt-oss-120b")
TOGETHER_CONTINUITY_MODEL = os.getenv(
    "TOGETHER_CONTINUITY_MODEL", "openai/gpt-oss-120b")
TOGETHER_SUMMARY_MODEL = os.getenv(
    "TOGETHER_SUMMARY_MODEL", "openai/gpt-oss-120b")
TOGETHER_PUBLISHER_MODEL = os.getenv(
    "TOGETHER_PUBLISHER_MODEL", TOGETHER_CONTINUITY_MODEL)
TOGETHER_PERFECTIONIST_MODEL = os.getenv(
    "TOGETHER_PERFECTIONIST_MODEL", TOGETHER_WRITER_MODEL)

TOGETHER_MODELS = {
    "default": TOGETHER_DEFAULT_MODEL,
    "profile": TOGETHER_PROFILE_MODEL,
    "storyteller": TOGETHER_PLANNER_MODEL,
    "launch_planner": TOGETHER_PLANNER_MODEL,
    "writer": TOGETHER_WRITER_MODEL,
    "reviewer": TOGETHER_REVIEWER_MODEL,
    "perfectionist": TOGETHER_PERFECTIONIST_MODEL,
    "summary": TOGETHER_SUMMARY_MODEL,
    "continuity": TOGETHER_CONTINUITY_MODEL,
    "publisher": TOGETHER_PUBLISHER_MODEL,
}


def _int_env(name: str, default: int) -> int:
    return int(os.getenv(name, str(default)))


# Explicit output budgets keep long structured JSON and chapter drafts from
# inheriting provider defaults that are often too small for this pipeline.
TOGETHER_DEFAULT_MAX_TOKENS = _int_env("TOGETHER_DEFAULT_MAX_TOKENS", 4096)
TOGETHER_PROFILE_MAX_TOKENS = _int_env("TOGETHER_PROFILE_MAX_TOKENS", 4096)
TOGETHER_PLANNER_MAX_TOKENS = _int_env("TOGETHER_PLANNER_MAX_TOKENS", 12000)
TOGETHER_LAUNCH_PLANNER_MAX_TOKENS = _int_env(
    "TOGETHER_LAUNCH_PLANNER_MAX_TOKENS", 6000
)
TOGETHER_WRITER_MAX_TOKENS = _int_env("TOGETHER_WRITER_MAX_TOKENS", 7000)
TOGETHER_REVIEWER_MAX_TOKENS = _int_env("TOGETHER_REVIEWER_MAX_TOKENS", 4096)
TOGETHER_CONTINUITY_MAX_TOKENS = _int_env("TOGETHER_CONTINUITY_MAX_TOKENS", 12000)
TOGETHER_SUMMARY_MAX_TOKENS = _int_env("TOGETHER_SUMMARY_MAX_TOKENS", 1024)
TOGETHER_PUBLISHER_MAX_TOKENS = _int_env("TOGETHER_PUBLISHER_MAX_TOKENS", 4096)
TOGETHER_PERFECTIONIST_MAX_TOKENS = _int_env(
    "TOGETHER_PERFECTIONIST_MAX_TOKENS", TOGETHER_WRITER_MAX_TOKENS
)

TOGETHER_MAX_TOKENS = {
    "default": TOGETHER_DEFAULT_MAX_TOKENS,
    "profile": TOGETHER_PROFILE_MAX_TOKENS,
    "storyteller": TOGETHER_PLANNER_MAX_TOKENS,
    "launch_planner": TOGETHER_LAUNCH_PLANNER_MAX_TOKENS,
    "writer": TOGETHER_WRITER_MAX_TOKENS,
    "reviewer": TOGETHER_REVIEWER_MAX_TOKENS,
    "perfectionist": TOGETHER_PERFECTIONIST_MAX_TOKENS,
    "summary": TOGETHER_SUMMARY_MAX_TOKENS,
    "continuity": TOGETHER_CONTINUITY_MAX_TOKENS,
    "publisher": TOGETHER_PUBLISHER_MAX_TOKENS,
}

# ---------------------------------------------------------------------------
# Retrieval (RAG over per-chapter summaries) — see stories/retrieval.py
# ---------------------------------------------------------------------------
TOGETHER_EMBEDDING_MODEL = os.getenv(
    "TOGETHER_EMBEDDING_MODEL", "intfloat/multilingual-e5-large-instruct"
)
# Top-K chapters to retrieve per Writer call. The last RAG_RECENT_WINDOW
# chapters are always included by recency, so they're excluded from RAG to
# avoid duplication.
RAG_TOP_K = int(os.getenv("RAG_TOP_K", "5"))
RAG_RECENT_WINDOW = int(os.getenv("RAG_RECENT_WINDOW", "2"))

MIN_CHAPTER_WORDS = int(os.getenv("MIN_CHAPTER_WORDS", "2000"))

# Default size of the first chapter batch written at story creation.
# The rest are drafted on demand via POST /api/stories/<id>/continue/.
DEFAULT_INITIAL_CHAPTERS = int(os.getenv("DEFAULT_INITIAL_CHAPTERS", "3"))

# ---------------------------------------------------------------------------
# stories_v2 — provider stack locked to Groq + Together AI
# ---------------------------------------------------------------------------
# Read by stories_v2/providers/router.py via os.getenv. Settings here exist
# so the router can also see them via django.conf.settings.
GROQ_API_KEY = os.getenv("GROQ_API_KEY", "")
GROQ_BASE_URL = os.getenv("GROQ_BASE_URL", "https://api.groq.com/openai/v1")

# Together AI is shared with v1 (TOGETHER_API_KEY already declared above).
TOGETHER_BASE_URL = os.getenv("TOGETHER_BASE_URL", "https://api.together.xyz/v1")

# Force Atlas $vectorSearch even on a non-SRV URI (e.g. local Atlas tunnel).
MONGODB_ATLAS_VECTOR = os.getenv("MONGODB_ATLAS_VECTOR", "")

# Optional GPTZero / Originality.ai key — enables the v2 humanisation
# detector gate. Leave blank to disable the external detector pass.
STORIES_V2_AI_DETECTOR_KEY = os.getenv("STORIES_V2_AI_DETECTOR_KEY", "")

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "%(asctime)s %(levelname)s [%(name)s] %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
    },
    "loggers": {
        "stories": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "stories_v2": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "myproject": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}
